package xiake.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import xiake.db.entity.AllFriend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALL_FRIEND".
*/
public class AllFriendDao extends AbstractDao<AllFriend, Void> {

    public static final String TABLENAME = "ALL_FRIEND";

    /**
     * Properties of entity AllFriend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Type = new Property(0, String.class, "type", false, "TYPE");
        public final static Property Mail_list = new Property(1, String.class, "mail_list", false, "MAIL_LIST");
    }


    public AllFriendDao(DaoConfig config) {
        super(config);
    }
    
    public AllFriendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALL_FRIEND\" (" + //
                "\"TYPE\" TEXT," + // 0: type
                "\"MAIL_LIST\" TEXT);"); // 1: mail_list
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALL_FRIEND\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AllFriend entity) {
        stmt.clearBindings();
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(1, type);
        }
 
        String mail_list = entity.getMail_list();
        if (mail_list != null) {
            stmt.bindString(2, mail_list);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AllFriend entity) {
        stmt.clearBindings();
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(1, type);
        }
 
        String mail_list = entity.getMail_list();
        if (mail_list != null) {
            stmt.bindString(2, mail_list);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public AllFriend readEntity(Cursor cursor, int offset) {
        AllFriend entity = new AllFriend( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // type
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // mail_list
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AllFriend entity, int offset) {
        entity.setType(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMail_list(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(AllFriend entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(AllFriend entity) {
        return null;
    }

    @Override
    public boolean hasKey(AllFriend entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
