package xiake.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import xiake.db.entity.User;
import xiake.db.entity.SmallMoney;
import xiake.db.entity.FriendAbout;
import xiake.db.entity.NewFriend;
import xiake.db.entity.AllFriend;
import xiake.db.entity.MailList;
import xiake.db.entity.ChatRecord;
import xiake.db.entity.Data;
import xiake.db.entity.Bill;
import xiake.db.entity.AliFriend;

import xiake.db.dao.UserDao;
import xiake.db.dao.SmallMoneyDao;
import xiake.db.dao.FriendAboutDao;
import xiake.db.dao.NewFriendDao;
import xiake.db.dao.AllFriendDao;
import xiake.db.dao.MailListDao;
import xiake.db.dao.ChatRecordDao;
import xiake.db.dao.DataDao;
import xiake.db.dao.BillDao;
import xiake.db.dao.AliFriendDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig smallMoneyDaoConfig;
    private final DaoConfig friendAboutDaoConfig;
    private final DaoConfig newFriendDaoConfig;
    private final DaoConfig allFriendDaoConfig;
    private final DaoConfig mailListDaoConfig;
    private final DaoConfig chatRecordDaoConfig;
    private final DaoConfig dataDaoConfig;
    private final DaoConfig billDaoConfig;
    private final DaoConfig aliFriendDaoConfig;

    private final UserDao userDao;
    private final SmallMoneyDao smallMoneyDao;
    private final FriendAboutDao friendAboutDao;
    private final NewFriendDao newFriendDao;
    private final AllFriendDao allFriendDao;
    private final MailListDao mailListDao;
    private final ChatRecordDao chatRecordDao;
    private final DataDao dataDao;
    private final BillDao billDao;
    private final AliFriendDao aliFriendDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        smallMoneyDaoConfig = daoConfigMap.get(SmallMoneyDao.class).clone();
        smallMoneyDaoConfig.initIdentityScope(type);

        friendAboutDaoConfig = daoConfigMap.get(FriendAboutDao.class).clone();
        friendAboutDaoConfig.initIdentityScope(type);

        newFriendDaoConfig = daoConfigMap.get(NewFriendDao.class).clone();
        newFriendDaoConfig.initIdentityScope(type);

        allFriendDaoConfig = daoConfigMap.get(AllFriendDao.class).clone();
        allFriendDaoConfig.initIdentityScope(type);

        mailListDaoConfig = daoConfigMap.get(MailListDao.class).clone();
        mailListDaoConfig.initIdentityScope(type);

        chatRecordDaoConfig = daoConfigMap.get(ChatRecordDao.class).clone();
        chatRecordDaoConfig.initIdentityScope(type);

        dataDaoConfig = daoConfigMap.get(DataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        billDaoConfig = daoConfigMap.get(BillDao.class).clone();
        billDaoConfig.initIdentityScope(type);

        aliFriendDaoConfig = daoConfigMap.get(AliFriendDao.class).clone();
        aliFriendDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        smallMoneyDao = new SmallMoneyDao(smallMoneyDaoConfig, this);
        friendAboutDao = new FriendAboutDao(friendAboutDaoConfig, this);
        newFriendDao = new NewFriendDao(newFriendDaoConfig, this);
        allFriendDao = new AllFriendDao(allFriendDaoConfig, this);
        mailListDao = new MailListDao(mailListDaoConfig, this);
        chatRecordDao = new ChatRecordDao(chatRecordDaoConfig, this);
        dataDao = new DataDao(dataDaoConfig, this);
        billDao = new BillDao(billDaoConfig, this);
        aliFriendDao = new AliFriendDao(aliFriendDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(SmallMoney.class, smallMoneyDao);
        registerDao(FriendAbout.class, friendAboutDao);
        registerDao(NewFriend.class, newFriendDao);
        registerDao(AllFriend.class, allFriendDao);
        registerDao(MailList.class, mailListDao);
        registerDao(ChatRecord.class, chatRecordDao);
        registerDao(Data.class, dataDao);
        registerDao(Bill.class, billDao);
        registerDao(AliFriend.class, aliFriendDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        smallMoneyDaoConfig.clearIdentityScope();
        friendAboutDaoConfig.clearIdentityScope();
        newFriendDaoConfig.clearIdentityScope();
        allFriendDaoConfig.clearIdentityScope();
        mailListDaoConfig.clearIdentityScope();
        chatRecordDaoConfig.clearIdentityScope();
        dataDaoConfig.clearIdentityScope();
        billDaoConfig.clearIdentityScope();
        aliFriendDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SmallMoneyDao getSmallMoneyDao() {
        return smallMoneyDao;
    }

    public FriendAboutDao getFriendAboutDao() {
        return friendAboutDao;
    }

    public NewFriendDao getNewFriendDao() {
        return newFriendDao;
    }

    public AllFriendDao getAllFriendDao() {
        return allFriendDao;
    }

    public MailListDao getMailListDao() {
        return mailListDao;
    }

    public ChatRecordDao getChatRecordDao() {
        return chatRecordDao;
    }

    public DataDao getDataDao() {
        return dataDao;
    }

    public BillDao getBillDao() {
        return billDao;
    }

    public AliFriendDao getAliFriendDao() {
        return aliFriendDao;
    }

}
