package xiake.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALI_FRIEND".
 */
@Entity
public class AliFriend {

    @Id(autoincrement = true)
    private Long id;
    private String img;
    private String nick;
    private Boolean isFriend;
    private String VipLv;
    private String num;
    private String mark;

    @Generated(hash = 1146103720)
    public AliFriend() {
    }

    public AliFriend(Long id) {
        this.id = id;
    }

    @Generated(hash = 1689355184)
    public AliFriend(Long id, String img, String nick, Boolean isFriend, String VipLv, String num, String mark) {
        this.id = id;
        this.img = img;
        this.nick = nick;
        this.isFriend = isFriend;
        this.VipLv = VipLv;
        this.num = num;
        this.mark = mark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public Boolean getIsFriend() {
        return isFriend;
    }

    public void setIsFriend(Boolean isFriend) {
        this.isFriend = isFriend;
    }

    public String getVipLv() {
        return VipLv;
    }

    public void setVipLv(String VipLv) {
        this.VipLv = VipLv;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    public String getMark() {
        return mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

}
