package xiake.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BILL".
 */
@Entity
public class Bill {

    @Id(autoincrement = true)
    private Long id;
    private String time;
    private String details;

    @Generated(hash = 1399599325)
    public Bill() {
    }

    public Bill(Long id) {
        this.id = id;
    }

    @Generated(hash = 421258879)
    public Bill(Long id, String time, String details) {
        this.id = id;
        this.time = time;
        this.details = details;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

}
