package xiake.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CHAT".
 */
@Entity
public class Chat {

    @Id(autoincrement = true)
    private Long id;
    private String chatTarget;
    private String time;
    private String myContent;
    private String hisContent;
    private String deleteContent;
    private String recallContent;
    private String myGift;
    private String myTransfer;
    private String hisGift;
    private String hisTransfer;

    @Generated(hash = 519536279)
    public Chat() {
    }

    public Chat(Long id) {
        this.id = id;
    }

    @Generated(hash = 1595052898)
    public Chat(Long id, String chatTarget, String time, String myContent, String hisContent, String deleteContent, String recallContent, String myGift, String myTransfer, String hisGift, String hisTransfer) {
        this.id = id;
        this.chatTarget = chatTarget;
        this.time = time;
        this.myContent = myContent;
        this.hisContent = hisContent;
        this.deleteContent = deleteContent;
        this.recallContent = recallContent;
        this.myGift = myGift;
        this.myTransfer = myTransfer;
        this.hisGift = hisGift;
        this.hisTransfer = hisTransfer;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChatTarget() {
        return chatTarget;
    }

    public void setChatTarget(String chatTarget) {
        this.chatTarget = chatTarget;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getMyContent() {
        return myContent;
    }

    public void setMyContent(String myContent) {
        this.myContent = myContent;
    }

    public String getHisContent() {
        return hisContent;
    }

    public void setHisContent(String hisContent) {
        this.hisContent = hisContent;
    }

    public String getDeleteContent() {
        return deleteContent;
    }

    public void setDeleteContent(String deleteContent) {
        this.deleteContent = deleteContent;
    }

    public String getRecallContent() {
        return recallContent;
    }

    public void setRecallContent(String recallContent) {
        this.recallContent = recallContent;
    }

    public String getMyGift() {
        return myGift;
    }

    public void setMyGift(String myGift) {
        this.myGift = myGift;
    }

    public String getMyTransfer() {
        return myTransfer;
    }

    public void setMyTransfer(String myTransfer) {
        this.myTransfer = myTransfer;
    }

    public String getHisGift() {
        return hisGift;
    }

    public void setHisGift(String hisGift) {
        this.hisGift = hisGift;
    }

    public String getHisTransfer() {
        return hisTransfer;
    }

    public void setHisTransfer(String hisTransfer) {
        this.hisTransfer = hisTransfer;
    }

}
