package xiake.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DATA".
 */
@Entity
public class Data {
    private String my_info;
    private String new_friend_list;
    private String allfriend;

    @Generated(hash = 2135787902)
    public Data() {
    }

    @Generated(hash = 1042126894)
    public Data(String my_info, String new_friend_list, String allfriend) {
        this.my_info = my_info;
        this.new_friend_list = new_friend_list;
        this.allfriend = allfriend;
    }

    public String getMy_info() {
        return my_info;
    }

    public void setMy_info(String my_info) {
        this.my_info = my_info;
    }

    public String getNew_friend_list() {
        return new_friend_list;
    }

    public void setNew_friend_list(String new_friend_list) {
        this.new_friend_list = new_friend_list;
    }

    public String getAllfriend() {
        return allfriend;
    }

    public void setAllfriend(String allfriend) {
        this.allfriend = allfriend;
    }

}
