package xiake.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "FRIEND_ABOUT".
 */
@Entity
public class FriendAbout {

    @Id(autoincrement = true)
    private Long id;
    private String imgPath;
    private String nickName;
    private Boolean no_disturb;
    private Boolean star_target;
    private String background;
    private String remark;
    private Boolean stick;
    private String chatContent;

    @Generated(hash = 782925306)
    public FriendAbout() {
    }

    public FriendAbout(Long id) {
        this.id = id;
    }

    @Generated(hash = 1595440008)
    public FriendAbout(Long id, String imgPath, String nickName, Boolean no_disturb, Boolean star_target, String background, String remark, Boolean stick, String chatContent) {
        this.id = id;
        this.imgPath = imgPath;
        this.nickName = nickName;
        this.no_disturb = no_disturb;
        this.star_target = star_target;
        this.background = background;
        this.remark = remark;
        this.stick = stick;
        this.chatContent = chatContent;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Boolean getNo_disturb() {
        return no_disturb;
    }

    public void setNo_disturb(Boolean no_disturb) {
        this.no_disturb = no_disturb;
    }

    public Boolean getStar_target() {
        return star_target;
    }

    public void setStar_target(Boolean star_target) {
        this.star_target = star_target;
    }

    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Boolean getStick() {
        return stick;
    }

    public void setStick(Boolean stick) {
        this.stick = stick;
    }

    public String getChatContent() {
        return chatContent;
    }

    public void setChatContent(String chatContent) {
        this.chatContent = chatContent;
    }

}
