package xiake.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MAIL_LIST".
 */
@Entity
public class MailList {
    private String name;
    private Integer is_chatlist;
    private String id;
    private String icon;
    private Integer msg_num;
    private String chat_bg;
    private String com_time;
    private String recent_new;
    private Boolean isMute;
    private String chat_record;

    @Generated(hash = 1505605862)
    public MailList() {
    }

    @Generated(hash = 789071482)
    public MailList(String name, Integer is_chatlist, String id, String icon, Integer msg_num, String chat_bg, String com_time, String recent_new, Boolean isMute, String chat_record) {
        this.name = name;
        this.is_chatlist = is_chatlist;
        this.id = id;
        this.icon = icon;
        this.msg_num = msg_num;
        this.chat_bg = chat_bg;
        this.com_time = com_time;
        this.recent_new = recent_new;
        this.isMute = isMute;
        this.chat_record = chat_record;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIs_chatlist() {
        return is_chatlist;
    }

    public void setIs_chatlist(Integer is_chatlist) {
        this.is_chatlist = is_chatlist;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getMsg_num() {
        return msg_num;
    }

    public void setMsg_num(Integer msg_num) {
        this.msg_num = msg_num;
    }

    public String getChat_bg() {
        return chat_bg;
    }

    public void setChat_bg(String chat_bg) {
        this.chat_bg = chat_bg;
    }

    public String getCom_time() {
        return com_time;
    }

    public void setCom_time(String com_time) {
        this.com_time = com_time;
    }

    public String getRecent_new() {
        return recent_new;
    }

    public void setRecent_new(String recent_new) {
        this.recent_new = recent_new;
    }

    public Boolean getIsMute() {
        return isMute;
    }

    public void setIsMute(Boolean isMute) {
        this.isMute = isMute;
    }

    public String getChat_record() {
        return chat_record;
    }

    public void setChat_record(String chat_record) {
        this.chat_record = chat_record;
    }

}
