package xiake.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NEW_FRIEND".
 */
@Entity
public class NewFriend {
    private String name;
    private Integer is_chatlist;
    private Long id;
    private String icon;
    private Integer msg_num;
    private String chat_bg;
    private String com_time;
    private String recent_new;
    private Boolean isMute;
    private String chat_record;
    private String request_msg;
    private Boolean request_state;

    @Generated(hash = 163516704)
    public NewFriend() {
    }

    @Generated(hash = 2099793108)
    public NewFriend(String name, Integer is_chatlist, Long id, String icon, Integer msg_num, String chat_bg, String com_time, String recent_new, Boolean isMute, String chat_record, String request_msg, Boolean request_state) {
        this.name = name;
        this.is_chatlist = is_chatlist;
        this.id = id;
        this.icon = icon;
        this.msg_num = msg_num;
        this.chat_bg = chat_bg;
        this.com_time = com_time;
        this.recent_new = recent_new;
        this.isMute = isMute;
        this.chat_record = chat_record;
        this.request_msg = request_msg;
        this.request_state = request_state;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIs_chatlist() {
        return is_chatlist;
    }

    public void setIs_chatlist(Integer is_chatlist) {
        this.is_chatlist = is_chatlist;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getMsg_num() {
        return msg_num;
    }

    public void setMsg_num(Integer msg_num) {
        this.msg_num = msg_num;
    }

    public String getChat_bg() {
        return chat_bg;
    }

    public void setChat_bg(String chat_bg) {
        this.chat_bg = chat_bg;
    }

    public String getCom_time() {
        return com_time;
    }

    public void setCom_time(String com_time) {
        this.com_time = com_time;
    }

    public String getRecent_new() {
        return recent_new;
    }

    public void setRecent_new(String recent_new) {
        this.recent_new = recent_new;
    }

    public Boolean getIsMute() {
        return isMute;
    }

    public void setIsMute(Boolean isMute) {
        this.isMute = isMute;
    }

    public String getChat_record() {
        return chat_record;
    }

    public void setChat_record(String chat_record) {
        this.chat_record = chat_record;
    }

    public String getRequest_msg() {
        return request_msg;
    }

    public void setRequest_msg(String request_msg) {
        this.request_msg = request_msg;
    }

    public Boolean getRequest_state() {
        return request_state;
    }

    public void setRequest_state(Boolean request_state) {
        this.request_state = request_state;
    }

}
