package xiake.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SMALL_MONEY".
 */
@Entity
public class SmallMoney {

    @Id(autoincrement = true)
    private Long id;
    private String pay;
    private String kiting;
    private String payTime;
    private String kitingTime;
    private String getkitingTime;
    private String payMoney;
    private String kitingMoney;
    private String payBank;
    private String kitingBank;

    @Generated(hash = 1053614681)
    public SmallMoney() {
    }

    public SmallMoney(Long id) {
        this.id = id;
    }

    @Generated(hash = 2089432387)
    public SmallMoney(Long id, String pay, String kiting, String payTime, String kitingTime, String getkitingTime, String payMoney, String kitingMoney, String payBank, String kitingBank) {
        this.id = id;
        this.pay = pay;
        this.kiting = kiting;
        this.payTime = payTime;
        this.kitingTime = kitingTime;
        this.getkitingTime = getkitingTime;
        this.payMoney = payMoney;
        this.kitingMoney = kitingMoney;
        this.payBank = payBank;
        this.kitingBank = kitingBank;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPay() {
        return pay;
    }

    public void setPay(String pay) {
        this.pay = pay;
    }

    public String getKiting() {
        return kiting;
    }

    public void setKiting(String kiting) {
        this.kiting = kiting;
    }

    public String getPayTime() {
        return payTime;
    }

    public void setPayTime(String payTime) {
        this.payTime = payTime;
    }

    public String getKitingTime() {
        return kitingTime;
    }

    public void setKitingTime(String kitingTime) {
        this.kitingTime = kitingTime;
    }

    public String getGetkitingTime() {
        return getkitingTime;
    }

    public void setGetkitingTime(String getkitingTime) {
        this.getkitingTime = getkitingTime;
    }

    public String getPayMoney() {
        return payMoney;
    }

    public void setPayMoney(String payMoney) {
        this.payMoney = payMoney;
    }

    public String getKitingMoney() {
        return kitingMoney;
    }

    public void setKitingMoney(String kitingMoney) {
        this.kitingMoney = kitingMoney;
    }

    public String getPayBank() {
        return payBank;
    }

    public void setPayBank(String payBank) {
        this.payBank = payBank;
    }

    public String getKitingBank() {
        return kitingBank;
    }

    public void setKitingBank(String kitingBank) {
        this.kitingBank = kitingBank;
    }

}
